---

- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Get quote
      ansible.builtin.shell: fortune -s
      register: quote

    - name: Print some facts
      ansible.builtin.debug:
        msg: "{{ quote.stdout_lines | replace('\\t','')}}"
