---

- hosts: all
  gather_facts: false
  tasks:
    - name: Install fortune
      ansible.builtin.apt:
        update_cache: true
        name: fortune-mod
        state: present
      become: yes
      
    - name: Get quote
      ansible.builtin.shell: fortune -s
      register: quote

    - name: Print some facts
      ansible.builtin.debug:
        msg: "{{ quote.stdout_lines | replace('\\t','')}}"
